; Script generated by the Inno Setup Script Wizard and Claude Sonnet 4.6 by ABATBeliever.
; Please build via scripts/build.bat before run this iss file.
; Inno Setup is here : https://jrsoftware.org/isdl.ph
; Do not locate in non-ASCII Path
#define MyAppName "VELA Browser"
#define MyAppVersion "2.1.3.0"
#define MyAppPublisher "ABATBeliever"
#define MyAppURL "https://abatbeliever.net/software/bin/VELABrowser"
#define MyAppExeName "VELABrowser.exe"
#define MyAppOutputName "VELABrowser-x64-Installer"
[Setup]
AppId={{5F37F586-A230-4D6D-8912-E1DE12083A7A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
VersionInfoVersion={#MyAppVersion}
VersionInfoDescription={#MyAppOutputName}
VersionInfoProductName={#MyAppOutputName}
VersionInfoProductVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
DefaultDirName={autopf}\VELABrowserx64
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=./LICENSE-inno.txt
;PrivilegesRequired=lowest
OutputDir=..\
OutputBaseFilename={#MyAppOutputName}
SetupIconFile=..\img\icon-win.ico
SolidCompression=yes
WizardStyle=classic
[Languages]
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"
[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
[Files]
Source: "..\VELABrowser.dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent